languageCode = "ja-jp"
# Missing translations will default to this content language
defaultContentLanguage = "ja"
baseURL = "https://medicalnote.github.io/"
title =  "Medical Note(メディカルノート) techブログ"
# filesystem path to write files to
publishDir = "dist"
author = "Medical Note Tech"
copyright = "Medical Note All rights reserved."
config = "config.toml"
# Missing translations will default
# if true, auto-detect Chinese/Japanese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
hasCJKLanguage =  true
layoutDir = "layouts"
# theme to use (located by default in /themes/THEMENAME/)
themesDir = "themes"
theme = "minimal"
canonifyurls = true
[params]
    author = "Medical Note Tech"
    description = "株式会社メディカルノートの技術ブログ"
    githubUsername = "medicalnote"
    accent = "#139BBA"
    showBorder = true
    backgroundColor = "white"
    font = "Sawarabi Gothic" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "html,xml", "javascript", "ruby", "swift"]
    defaultAuthor = "Medical Note Tech"
  [params.authors]
    [params.authors.kawamoto]
        name = "河本"
        bio = "CTO"
    [params.authors.yamada]
        name = "山田"
        bio = "メディア事業"
    [params.authors.nagatomo]
        name = "長友"
        bio = "メディア事業"
    [params.authors.takada]
        name = "高田"
        bio = "医療相談"
    [params.authors.yokoo]
        name = "横尾"
        bio = "医療相談"
    [params.authors.maeda]
        name = "前田"
        bio = "医療相談"
    [params.authors.sakurai]
        name = "櫻井"
        bio = "Tech"
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "投稿記事"
    weight = 2


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/medicalnote/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/medicalnote_co/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.facebook.com/medicalnote.jp/"
    name = "facebook"
    weight = 3

[[menu.icon]]
    url = "mailto:info@medicalnote.co.jp"
    name = "お問い合わせ"
    weight = 4