version: 2
jobs:
  build:
    working_directory: ~/techblog
    machine: true
    steps:
      - checkout
      - run:
          name: install hugo
          command: go get -v github.com/gohugoio/hugo
      - run:
          name: build hugo
          command: hugo -t minimal
      - save_cache:
          key: techblog-{{ epoch }}
          paths:
            - ~/techblog
  approve:
    working_directory: ~/techblog
    machine: true
    steps:
      - run:
          name: noope
          command: echo noope
  deploy:
    working_directory: ~/techblog
    machine: true
    steps:
      - restore_cache:
          keys:
            - techblog
      - run:
          name: cd dist
          command: cd dist
      - run:
          name: git user name
          command: git config --global user.name "${GIT_USER_NAME}"
      - run:
          name: git user email
          command: git config --global user.email "${GIT_USER_EMAIL}"
      - run:
          name: git clone
          command: cd dist && git clone git@github.com:medicalnote/medicalnote.github.io.git
      - run:
          name: change git repositly
          command: git remote set-url origin git@github.com:medicalnote/medicalnote.github.io.git
      - run:
          name: add
          command: cd dist && git add --all
      - run:
          name: commit
          command: cd dist && git commit -m "[ci skip] dist"
      - run:
          name: push
          command: cd dist && git push -f origin

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master